services:
  app:
    build: .
    env_file: .env
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
      - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: codespace
    ports:
      - "3306:3306"


